import csv
with open('fix/alimenticios.csv', 'w') as f:
    csv_writer = csv.writer(f)
    csv_writer.writerow([
        'nome_en','nome_alt','nome_br','origem','funcao_principal','referencia'
    ])
    rows = [
        ['Cocoa Butter Substitute','Cocoa Butter Equivalent ','Substituto da Manteiga de Cacau','Natural a partir de plantas como a palma açafrão-dos-tintureiros girassol ou óleo de coco ','Glaceante destinado a ser aplicado na superfície externa de um alimento para lhe conferir uma aparência brilhante e um revestimento protetor que evite perdas de substâncias devido à exposição do produto aumentando assim sua vida útil','[A1] [D] [Q] [193]'],
        ['Limonene','l-p-Mentha-18-diene','Limoneno','Artificial a partir do processo de separação por centrifugação e destilação por arraste de vapor do óleo de casca de plantas cítricas','Aromatizante destinado a conferir ou reforçar o aroma e/ou sabor dos alimentos','[A1] [D] [91]'],
        ['Anise alcohol','Anisyl Alcohol','Álcool anisílico','Artificial a partir da adição de hidrogênio ao composto p-metoxibenzaldeído e é um álcool encontrado naturalmente em vagens de baunilha e nas sementes de anis','Aromatizante destinado a conferir ou reforçar o aroma e/ou sabor dos alimentos','[D] [110] [111] [194]'],
        ['Acid yellow 23','Tartrazine (INS 102)','Tartrazina','Artificial a partir do ácido 45-di-hidroxi-5-oxo-1-(4-sulfofenil)-4-(4-sulfofenil-azo)-1H-pirazol-3-carboxílico','Corante destinado a conferir intensificar ou restaurar a cor de um alimento.','[A1] [B] [D]'],
        ['Citronellol','DL-Citronellol','Citronelol','Artificial a partir da hidrogenação de nerol e geraniol compostos encontrados naturalmente nos óleos essenciais de capim-limão óleo de rosacitronelalavandalaranja-natal etc.','Aromatizante destinado a conferir ou reforçar o aroma e/ou sabor dos alimentos','[A1] [A2] [D] [127]'],
        ['Nerol','(Z)-Geraniol','Nerol','Artificial a partir de um processo de reações com o mirceno (encontrado na maconha manga lúpulo capim-limão e manjericão)','Aromatizante destinado a conferir ou reforçar o aroma e/ou sabor dos alimentos','[F] [127] [195]'],
        ['Polyvinyl Acetate','PVA','Acetato de Polivinila','Artificial a partir da repetição química das estruturas moleculares do acetato de vinila com aceleradores de reação e processos de secagem a vácuo e lavagem','Substância mastigatória em base de goma de mascar','[A1] [E]'],
        ['Sodium benzoate','INS  211','Benzoato de sódio ','Artificial a partir da dissolução do ácido benzólico com soda cáustica','Conservante destinado a inibir o crescimento de microrganismos durante a fabricação e estocagem do produto ou protegê-los da contaminação inadvertida durante o uso','[A1] [A2] [B] [D] [135]'],
        ['Monosodium Glutamate','MSG','Glutamato monossódico','Artificial a partir da fermentação bacteriana com a glucose açúcares de ingredientes vegetais como cana-de-açúcar beterraba mandioca ou milho','Realçador de sabor destinado a ressaltar ou realçar o sabor/aroma de um alimento','[A1] [B] [D] [196]'],
        ['Cera alba','Beeswax','Cera de abelha','Artificial a partir da retirada da cera no favo de mel passando por processos de aquecimento derretimento e filtragem ','Glaceante destinado a ser aplicado na superfície externa de um alimento para lhe conferir uma aparência brilhante e um revestimento protetor que evite perdas de substâncias devido à exposição do produto aumentando assim sua vida útil','[A1] [A2] [D] [143]'],
        ['Potassium sorbate','Sorbistat potassium','Sorbato de potássio','Artificial a partir do ácido sórbico o qual é encontrado naturalmente em frutas como laranja tangerina limão caju e maracujá','Conservante destinado a inibir o crescimento de microrganismos durante a fabricação e estocagem do produto ou protegê-los da contaminação inadvertida durante o uso','[A2] [N] [J] '],
        ['Hydrochloric acid','Acidum hydrochloricum','Ácido clorídrico','Artificial a partir da reação de sal (cloreto de sódio) com ácido sulfúrico mas ocorre naturalmente no estômago de mamíferos','Acidulante destinado a aumentar a acidez ou conferir um sabor ácido aos alimentos.','[A1] [A2] [B] [D] [13]'],
        ['Butylated hydroxytoluene','BHT','Hidroxitolueno butilado','Artificial produzido a partir do petróleo','Antioxidante destinado a evitar que os demais ingredientes degradem por oxidação','[A2] [D] [157]'],
        ['Anacardium occidentale nut oil','Cashew Nut oil','Óleo vegetal da castanha do caju','Natural a partir da extração por prensagem a frio (esmagamento) da castanha-de-caju','Glaceante destinado a ser aplicado na superfície externa de um alimento para lhe conferir uma aparência brilhante e um revestimento protetor que evite perdas de substâncias devido à exposição do produto aumentando assim sua vida útil','[A1] [A2] [Q] [156]'],
        ['Erythorbic Acid','D-Araboascorbic Acid','Ácido eritórbico','Artificial a partir da a biofermentação do açúcar comumente produzido do amido de milho a dextrose','Antioxidante destinado a evitar que os demais ingredientes degradem por oxidação','[A1] [A2] [D] [R] [197] [198]'],
        ['Sorbitol','D-Glucitol','Sorbitol','Artificial a partir da adição de hidrogênios na glicose e pode ser encontrado naturalmente em frutas como pêras e ameixas','Edulcorante destinado a conferir sabor doce ao alimento','[A1] [B] [199] [200]'],
        ['Pigment Metal 3','INS 175','Ouro','Artificial a partir da extração do minério na natureza passando por esmagamento mecânico e refinamento eletrolítico ou químico (com o uso de cloro ácido nítrico ou ácido sulfurico)','Corante destinado a conferir intensificar ou restaurar a cor de um alimento.','[B] [201] [202]'],
        ['Sodium Acid Pyrophosphate','SAAP','Pirofosfato ácido de sódio','Artificial a partir da neutralização parcial do ácido fosfóricode grau alimentício com soda caústica ou carbonato de sódio para formar o sal fosfato monossódico o qual é desidratado a 250°C','Agente tampão destinado a estabilizar o pH dos produtos alimentícios','[A1][S] [205]'],
        ['Sodium bicarbonate','Baking soda','Bicarbonato de sódio','Artificial a partir das etapas de reação do dióxido de carbono amônia água e cloreto de sódio no chamado processo Solvay','Fermento Químico destinado aumentar o volume da massa através da liberação de gás por parte das substâncias do fermento','[A1] [B] [23] [206]'],
        ['Monocalcium Phosphate','Calcium Phosphate','Fosfato monocálcio','Artificial a partir do ácido fosfórico com o carbonato de cálcio geralmente provido da rocha calcário ','Melhorador de Farinha substância agregada à farinha destinada a melhorar sua qualidade tecnológica para os fins a que se destina.','[A1] [D] [207]'],
        ['Ethanol','Alcohol','Álcool etílico','Artificial a partir da fermentação de vegetais ricos em açúcares ou por hidratação do etileno','Aromatizante destinado a conferir ou reforçar o aroma e/ou sabor dos alimentos','[A1] [D] [2] [14] [208]'],
        ['Caramel Color','Caramel','Corante Caramelo (IIIIII IV)','Artificial a partir do aquecimento de carboidratos compostos por frutose dextrose (glicose) açúcar invertido sacarose xarope de malte melaço e/ou hidrolisados de amido sob temperatura controlada podendo haver adição de ácidos bases e/ou sais','Corante destinado a conferir intensificar ou restaurar a cor de um alimento.','[A1] [B] [D] [209]'],
        ['Maize starch','Corn Starch','Amido de milho','Natural a partir do milho e tem sua extração por moagem via úmida cuja finalidade é o aumento de eficiência na separação das partes que compõe o grão de milho: gérmen endosperma (90% constituido por amido) e pericarpo','Espessante destinado a aumentar a viscosidade de um alimento.','[D] [210]'],
        ['Modified Starch','Modified Starch','Amido modificado','Artificial a partir do amido provido do milho ou mandioca que tem sua cadeia química alterada por ações enzimáticas térmicas ou por substâncias especificas como ácidos.','Umectante destinado a proteger os alimentos da perda de umidade em ambiente de baixa umidade relativa ou destinado a facilitar a dissolução de uma substância seca em meio aquoso.','[A] [D] [211]'],
        ['Sucrose','Granulated Sugar','Açúcar','Natural a partir da cana-de-açúcar ou beterraba','Açúcar nutritivo destinado a nutrir e trazer o sabor adocicado ao alimento','[A1] [T] '],
        ['Invert Sugar Syrup','Invert Sugar','Açúcar invertido','Natural a partir do aquecimento da sacarose (açúcar) provida da cana-de-açúcar ou beterraba e água ','Açúcar nutritivo destinado a nutrir e trazer o sabor adocicado ao alimento','[A1] [T]'],
        ['Maltodextrin','','Maltodextrina','Artifical a partir da quebra parcial por água do amido comestível','Agente degomante destinado a favorecer a remoção ou separação de gomas ou mucilagens.','[A1] [D]'],
        ['','INS 330','Ácido cítrico','Artificial a partir da fermetação de uma fonte de carboidrato como a beterraba crua e a cana-de-açúcar através do cultivo do fungo Aspergillus niger no sistema','Acidulante destinado a Antioxidante destinado a evitar que os demais ingredientes degradem por oxidação','[A1] [D]'],
        ['Aspartame','APM','Aspartame','Artificial a partir de fermentação e síntese microbiana para formação da fenilalanina e do ácido aspártico','Edulcorante destinado a conferir sabor doce ao alimento','[A1] [D] [212]'],
        ['Acesulfame Potassium','Acesulfame K ( E950)','Acessulfame de potássio','Artificial a partir d','Edulcorante destinado a conferir sabor doce ao alimento','[A] [D]'],
        ['Bordeaux red','','Vermelho Bordeaux S','Artificial a partir da tinta do alcatrão de carvão','Corante destinado a conferir intensificar ou restaurar a cor de um alimento.','[B] [D][213]'],
        ['','','Azul indigotina','Artificial a partir ','Corante destinado a conferir intensificar ou restaurar a cor de um alimento.','[A1] [B]'],
        ['CI Food Blue 1','INS 133','Azul brilhante','Artificial a partir de hidrocarbonetos aromáticos derivados do petróleo.','Corante destinado a conferir intensificar ou restaurar a cor de um alimento.','[A1] [B] [D][214]'],
        ['Folic acid','Pteroylglutamic Acid','Ácido fólico','Artificial a partir da reação 23-dibromopropanoácido p-aminobenzoil-L-glutâmico e e 23-dibromopropanal e é encontrado naturalmente em vegetais verde-escuro como aspargos e espinafre frutas como abacate laranja grãos e sementes como lentilha arroz feijão ervilha nozes carnes frutos do mar e ovo.','Melhorador de Farinha destinado a quando agregado à farinha melhorar sua qualidade nutritiva.','[A1] [B] [215] [216]'],
        ['Starch','Cassava starch','Fécula/Povilho doce','Natural a partir das partes subterrâneas comestíveis da mandioca (raízes) e lavagem da massa ralada passando por secagem solar','Agente de Massa destinado a proporcionar o aumento de volume e/ou da massa dos alimentos sem contribuir significamente para o valor energético do alimento./ Espessante destinado a aumentar a viscosidade de um alimento. ','[A1] [B] [217] [218] [219]'],
        ['Salt','Sodium chloride','Sal','Natural a partir da cristalização dos sais dissolvidos na água do mar através de evaporadores industriais','Realçador de Sabor destinado a ressar ou realçar o sabor/aroma de um alimento.','[A1] [D] [44]'],
        ['Olein','Oleic acid','Oleína vegetal','Natural a partir da palma sementes da uva milho azeitona e outros transformados em óleo geralmente através do método por prensagem.','Emulsionante/Emulsificante destinado a tornar possível a formação ou manutenção de uma mistura uniforme de duas ou mais fases imiscíveis no alimento.','[A1] [D] [220]'],
        ['Hydrolyzed protein','Partially Hydrolyzed Proteins','Proteína hidrolisada','Artificial a partir de processos com a caseína e outros produtos lácteos como proteína de soro de leite; de tecido animal incluindo gelatina tecido animal desengordurado e albumina de ovo; ou a partir de leveduras; e de produtos de proteína de soja proteína de trigo produtos ou outras fontes vegetais adequadas e seguras','Estabilizante destinado a tornar possível a manutenção de uma dispersão uniforme de duas ou mais substâncias imiscíveis em um alimento. / Realçador de Sabor destinado a ressar ou realçar o sabor/aroma de um alimento.','[A1] [D] [N]'],
        ['Disodium Inosinate','Sodium Inosinate','Inosinato dissódico','Artificial a partir de carnes como frango  ou a partir da goma de tapioca','Realçador de Sabor destinado a ressar ou realçar o sabor/aroma de um alimento.','[A1] [D] [221]'],
        ['Caffeine','137-Trimethylxanthine','Cafeína','Natural a partir dos grãos de café folhas de chá e de mate nas sementes de cacau e em várias partes do guaraná','Realçador de Sabor destinado a ressar ou realçar o sabor/aroma de um alimento.','[A1] [D] [222] [223]'],
        ['Gluten','Wheat Gluten','Glúten','Natural a partir de cereais como a cevada trigo centeio etc. e é obtido indivialmente geralmente a partir da farinha de trigo lavada e secada em estufa.','Agente de Massa destinado a proporcionar o aumento de volume e/ou da massa dos alimentos.','[A] [B] [224] [225]'],
        ['Iron','Ferrum','Ferro','Natural a partir da extração do minério de ferro e é encontrado naturalmente em ovos carnes animais leguminosas folhas verdes sementes','Nutriente destinado a fornecer energia e nutrição necessária para o crescimento desenvolvimento e manutenção da saúde do consumidor.','[D][I][V] [226]'],
        ['Calcium Carbonate','E 170','Carbonato de cálcio','Natural a partir da rocha cálcario (matéria-prima do giz)  que passa por processos de separação da água secagem e moagem do produto final','Antiumectante destinado a reduzir as características higroscópicas (absorção de água) dos alimentos e diminuir a tendência de adesão umas às outras das partículas individuais.','[A1] [B] [D] [227] [228]'],
        ['Zinc sulfate','','Sulfato de zinco','Natural a partir d','Nutriente destinado a fornecer energia e nutrição necessária para o crescimento desenvolvimento e manutenção da saúde do consumidor.','[A1] [B] [I] [V]'],
        ['','','Bicarbonato de amônio ','','Fermento químico','[A] [B]'],
        ['','','Lecitina de soja','','Emulsificante','[A] [B]'],
        ['','','Dióxido de silício','','Antiumectante','[A] [B]'],
        ['','','Fosfato tricálcio','','Antiumectante','[A] [B]'],
        ['','','Cúrcuma','Natural','Corante','[A] [B]'],
        ['','','Stevia','Natural','Edulcorante','[A] [B]'],
        ['','','Polidextrose','','','[A] [B]'],
        ['','','Pirofosfato férrico','','','[A] [B]'],
        ['','Ácido L ascórbico','Vitamina C','','Nutriente / Antioxidante','[A] [B]'],
        ['','Nicotinamida','Niacina','','Nutriente destinado a fornecer energia e nutrição necessária para o crescimento desenvolvimento e manutenção da saúde do consumidor.','[A] [B]'],
        ['','Riboflavina','Vitamina B2','','Nutriente destinado a fornecer energia e nutrição necessária para o crescimento desenvolvimento e manutenção da saúde do consumidor.','[A] [B]'],
        ['','Acetato de retinila','Vitamina A','','Nutriente destinado a fornecer energia e nutrição necessária para o crescimento desenvolvimento e manutenção da saúde do consumidor.','[A] [B]'],
        ['','Cloridrato de piridoxina','Vitamina B6','','Nutriente destinado a fornecer energia e nutrição necessária para o crescimento desenvolvimento e manutenção da saúde do consumidor.','[A] [B]'],
        ['','Colecalciferol','Vitamina D','','Nutriente destinado a fornecer energia e nutrição necessária para o crescimento desenvolvimento e manutenção da saúde do consumidor.','[A] [B]'],
        ['','Cianocobalamina','Vitamina B12','','Nutriente destinado a fornecer energia e nutrição necessária para o crescimento desenvolvimento e manutenção da saúde do consumidor.','[A] [B]'],
        ['','','Fibra alimentar','','','[A] [B]'],
        ['','','Sucralose','','Edulcorante','[A] [B]'],
        ['','','Frutose','Natural','','[A] [B]'],
        ['','','Sacarina sódica','','','[A] [B]'],
        ['','','Vitamina B1','','Nutriente destinado a fornecer energia e nutrição necessária para o crescimento desenvolvimento e manutenção da saúde do consumidor.','[A] [B]'],
        ['','','Beta glucana','','','[A] [B]'],
        ['','','Carbonato de magnésio','','','[A] [B]'],
        ['','','Fosfato dicálcio','','','[A] [B]'],
        ['','','Vitamina E','','Nutriente destinado a fornecer energia e nutrição necessária para o crescimento desenvolvimento e manutenção da saúde do consumidor.','[A] [B]'],
        ['','','Tiamina','','','[A] [B]'],
        ['','','Biotina','','','[A] [B]'],
        ['','','Taurina','','','[A] [B]'],
        ['','','Ácido pantotenico ','','','[A] [B]'],
        ['','','Monoglicerídeos','','Emulsificante','[A] [B]'],
        ['','','Diglicerídeos','','Emulsificante','[A] [B]'],
        ['','','Palmitato de ascorbila','','Antioxidante destinado a evitar que os demais ingredientes degradem por oxidação','[A] [B]'],
        ['','','Alfatocoferol ','','Antioxidante destinado a evitar que os demais ingredientes degradem por oxidação','[A] [B]'],
        ['','','Metionina','','Nutriente destinado a fornecer energia e nutrição necessária para o crescimento desenvolvimento e manutenção da saúde do consumidor.','[A] [B]'],
        ['','','Cloreto de colina','','Nutriente destinado a fornecer energia e nutrição necessária para o crescimento desenvolvimento e manutenção da saúde do consumidor.','[A] [B]'],
        ['','','Cloreto de sódio','','Nutriente destinado a fornecer energia e nutrição necessária para o crescimento desenvolvimento e manutenção da saúde do consumidor.','[A] [B]'],
        ['','','Cloreto de potássio','','Nutriente destinado a fornecer energia e nutrição necessária para o crescimento desenvolvimento e manutenção da saúde do consumidor.','[A] [B]'],
        ['','','Iodeto de cálcio','','Nutriente destinado a fornecer energia e nutrição necessária para o crescimento desenvolvimento e manutenção da saúde do consumidor.','[A] [B]'],
        ['','','Óxido de zinco','','Nutriente destinado a fornecer energia e nutrição necessária para o crescimento desenvolvimento e manutenção da saúde do consumidor.','[A] [B]'],
        ['','','Selenito de sódio','','Nutriente destinado a fornecer energia e nutrição necessária para o crescimento desenvolvimento e manutenção da saúde do consumidor.','[A] [B]'],
        ['','','Sulfato de cobre','','Nutriente destinado a fornecer energia e nutrição necessária para o crescimento desenvolvimento e manutenção da saúde do consumidor.','[A] [B]'],
        ['','','Sulfato de manganes ','','Nutriente destinado a fornecer energia e nutrição necessária para o crescimento desenvolvimento e manutenção da saúde do consumidor.','[A] [B]'],
        ['','B.H.T','Hidróxido de tolueno butilado','','Conservante','[A] [B]'],
        ['','','Lactose','Natural','','[A] [B]'],
        ['','','Pirofosfato tetrassódico','','Estabilizante','[A] [B]'],
        ['','','Tripolifosfato de sódio','','Estabilizante','[A] [B]'],
        ['','','Polifosfato de sódio','','Estabilizante','[A] [B]'],
        ['','','Ácido sórbico','','Conservante','[A] [B]'],
        ['','','Nisina','','Conservante','[A] [B]'],
        ['','','Goma xantana','Artificial a partir da fermentação química de um carboidrato (frutas e legumes por exemplo) com a bactéria Xanthomonas campestris','Estabilizante / Espessante','[A1] [B]'],
        ['','','Ácido fosfórico','','Acidulante','[A] [B]'],
        ['','','EDTA','Artificial a partir do etilenodiamina formaldeído e cianeto de sódio','Sequestrante destinado a formar ligações com cargas químicas susceptíveis de afetar negativamente a composição do produto alimentício','[A] [D] [104]'],
        ['','B.H.A.','','','Antioxidante','[A] [B]'],
        ['','','Ácido lático','','Acidulante','[A] [B]'],
        ['','','Xarope de glicose','','','[A] [B]'],
        ['','','Dióxido de titanio','','Corante','[A] [B]'],
        ['','','Citrato de sódio','','Estabilizante','[A] [B]'],
        ['','','Fermentado acético','','','[A] [B]'],
        ['','INS 223','Metabissulfito de sódio','','Conservante','[A] [B]'],
        ['','','Nitrito de sódio','','Conservante','[A] [B]'],
        ['','','Nitrato de sódio','','Conservante','[A] [B]'],
        ['','','Fermento lático','','','[A] [B]'],
        ['','','Ácido esteárico','','Glaceante','[A] [B]'],
        ['','INS 428','Gelatina','Natural','Gelificante','[A] [B]'],
        ['','INS 422','Glicerina','','Umectante','[A] [B]'],
        ['','','Omega 3 6 9','','','[A] [B]'],
        ['','','Propionato de cálcio','','Conservante','[A] [B]'],
        ['','','Estearoil 2 lactil lactato de cálcio','','Emulsificante','[A] [B]'],
        ['','','Carboximetilcelulose','','Espessante','[A] [B]'],
        ['','','Cera carnaúba','','','[A] [B]'],
        ['','','Cera candelila','','','[A] [B]'],
        ['','','Taumatina','','','[A] [B]'],
        ['','INS 913','Lanolina','','','[A] [B]'],
        ['','INS 1102','Glucose-oxidase','','Atioxidante','[A] [B]'],
        ['','','Talco','','Antiumectante','[A] [B]'],
        ['','','Isomalte','','Glaceante','[A] [B]'],
        ['','','Ácido ascórbico','','','[A] [B]'],
        ['','INS 327','Lactato de cálcio','','Melhorador de farinha destinado a','[A] [B]'],
        ['','INS 516','Sulfato de cálcio','','Melhorador de farinha destinado a','[A] [B]'],
        ['','INS 529','Óxido de cálcio','','Melhorador de farinha destinado a','[A] [B]'],
        ['','INS 1100','Alfa-amilase','','Melhorador de farinha destinado a','[A] [B]'],
        ['','INS 630','Ácido inosínico','','Realçador de sabor destinado a','[A] [B]'],
        ['','INS 967','Xilitol','','Umectante destinado a','[A] [B]'],
        ['','','Fumarato de sódio ','','',''],
        ['','','Goma Tara ','','',''],
        ['','','Celulose em pó ','','',''],
        ['','','Etilcelulose ','','',''],
        ['','','Alga Euchema processada','','',''],
        ['','','Hidroxipropilmetilcelulose','','',''],
        ['','','Ácido clorídrico Acidulante','','',''],
        ['','','Cloreto de potássio Gelificante','','',''],
        ['','','Cloreto de amônio','','',''],
        ['','','Cloreto de magnésio ','','',''],
        ['','','Silicato de cálcio e alúminio ','','',''],
        ['','','Gluconato de sódio ','','',''],
        ['','','Gluconato de potássio','','',''],
        ['','',' Bicarbonato de magnésio','','',''],
        ['','','Carbonato ácido de magnésio','','',''],
        ['','','Etillhidroxietilcelulose','','',''],
        ['','','Sesquicarbonato de sódio','','',''],
        ['','','Bicarbonato de potássio','','',''],
        ['','','Carbonato ácido de potássio','','',''],
        ['Hydrogenated lecithin','Hydriertes Lecithin','Lecitina Hidrogenada','Artificial a partir de processos de hidrogenização da lecitina a qual é extraída geralmente pelo processo de aquecimento e preciptação nos óleos de soja e milho ou isolada quimicamente das gemas de ovos','Emulsificante destinado a tornar as fases dos produtos alimentícios que não se misturam mais uniformes possível ','[A2] [D] [174] [175]'],
        ['Modified Food Starch','','Extrato de carvalho','','Aromatizante','[J]'],
        ['','','Poliglicerol polirricinoleato','','Emulsificante destinado a tornar as fases dos produtos alimentícios que não se misturam mais uniformes possível ','[D]'],
        ['Extra virgin olive oil','','Azeite de Oliva Extra Virgem','Natural a partir de azeitonas selecionadas e prensadas a frio imediatamente após a colheita','','[204] [203]'],
        ['','','Ágar','','','[B]'],
        ['','','Ácido fosfórico','','Acidulante destinado a aumentar a acidez ou conferIR um sabor ácido aos alimentos.','[A1] [D]'],
        ['Gamma-Cyclodextrin','','Bacillus thuringiensis','','Carrier',''],
        ['','','Streptomyces viridochromogenes','','',''],
        ['','','Agrobacterium tumefaciens','','',''],
        ['','','Xarope de milho','','',''],
        ['','','Fosfato de cálcio','','',''],
        ['','','Pirofosfato férrico','','',''],
        ['','','Pantotenato de cálcio','','',''],
        ['','','Riboflavina','','',''],
        ['','','Corante natural betacaroteno','','',''],
        ['','','Mononitrato de tiamina','','',''],
        ['','','Coca','','',''],
    ]
    csv_writer.writerows(rows)