# Generated by Django 4.0.4 on 2022-05-11 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_ingredientes_referencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientes',
            name='referencia',
            field=models.CharField(default='', max_length=255),
        ),
    ]
