# Generated by Django 4.0.4 on 2022-05-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_ingredientes_referencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientes',
            name='funcao_principal',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ingredientes',
            name='origem',
            field=models.CharField(max_length=255),
        ),
    ]
