# Generated by Django 4.0.4 on 2022-05-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_ingredientes_funcao_principal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientes',
            name='referencia',
            field=models.CharField(max_length=255),
        ),
    ]
